version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.27.4
  slack: circleci/slack@3.3.0

workflows:
  branch_publish:
    jobs:
      - orb-tools/lint:
          name: branch_lint
      - orb-tools/pack:
          name: branch_pack
          requires:
            - branch_lint
      - orb-tools/publish-dev:
          name: branch_publish
          orb-name: navikt/barkendeploy
          requires:
            - branch_pack
          alpha-version-ref: dev:$CIRCLE_BRANCH
          sha-version-ref: dev:$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7}
          publish-token-variable: CIRCLE_TOKEN_DEV
