version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.27.4
  slack: circleci/slack@3.3.0

workflows:
  branch_publish:
    jobs:
      - orb-tools/lint:
          name: branch_lint
      - orb-tools/pack:
          name: branch_pack
          requires:
            - branch_lint
      - orb-tools/publish-dev:
          name: branch_publish
          orb-name: navikt/barkendeploy
          requires:
            - branch_pack
          alpha-version-ref: dev:$CIRCLE_BRANCH
          sha-version-ref: dev:$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7}
          publish-token-variable: CIRCLE_TOKEN_DEV
  tag_release:
    jobs:
    - orb-tools/lint:
        name: release_lint
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v[0-9]+.[0-9].[0-9]/
    - orb-tools/pack:
        name: release_pack
        requires:
          - release_lint
    - release_await_approval:
        type: approval
        requires:
          - release_pack
    - orb-tools/publish:
        name: release_publish
        requires:
          - release_await_approval
        orb-ref: navikt/barkendeploy@$CIRCLE_TAG
