description: Loads environment variables and creates a deployment

parameters:
 deployments:
  description: Steps for creating deployments
  type: steps
  default: []

docker:
  - image: "navikt/deployment-cli:v0.1.9"
steps:
  - workspace-restore
  - load-persisted-env
  - steps: <<parameters.deployments>>